CREATE TABLE NetworkDevices (
    ID SERIAL PRIMARY KEY,
    DeviceName VARCHAR(255) NOT NULL,
    IPAddress INET NOT NULL,
    Username VARCHAR(255) NOT NULL,
    "Password" VARCHAR(255) NOT NULL,
    ConnectionType VARCHAR(255) NOT NULL,
    Port INT NOT NULL DEFAULT 22
);

CREATE TABLE NetworkProperty (
    ID SERIAL PRIMARY KEY,
    NetworkDeviceID INT REFERENCES NetworkDevices(ID) ON DELETE CASCADE,
    OS VARCHAR(255) NOT NULL,
    CPU INT NOT NULL,
    RAM INT NOT NULL
);

CREATE TABLE NetworkProtocols (
    ID SERIAL PRIMARY KEY,
    NetworkDeviceID INT REFERENCES NetworkDevices(ID) ON DELETE CASCADE,
    DHCP BOOLEAN NOT NULL,
    OSPF BOOLEAN NOT NULL
);

CREATE TABLE DHCPpools (
    ID SERIAL PRIMARY KEY,
    DHCPID INT,
    PoolName VARCHAR(255) NOT NULL,
    Network VARCHAR(255) NOT NULL,
    Gateway VARCHAR(255) NOT NULL,
    DNS VARCHAR(255) NOT NULL,
    DomainSearch VARCHAR(255) NOT NULL
);

CREATE TABLE OSPFInstances (
    ID SERIAL PRIMARY KEY,
    OSPFID INT NOT NULL,
    OSPFInstance INT NOT NULL
);

CREATE TABLE OSPFNetworks (
    ID SERIAL PRIMARY KEY,
    OSPFInstanceID INT REFERENCES OSPFInstances(ID) ON DELETE CASCADE,
    Network VARCHAR(255) NOT NULL,
    Mask VARCHAR(255) NOT NULL,
    Area VARCHAR(255) NOT NULL
);

